### ISSUE TITLE
Linux automatic particles simulation crashes

### ISSUE THREAD

**Issue by fanq15** [cv-rits/rain-rendering#12] opened 2021-12-22 06:37 UTC
Hi, thanks for your great work!
I am using the Ubuntu20.04 system to run your code.
But I met a problem when running `python3 main.py --dataset customdb --intensity 25 --frame_end 60`:
```
Building internal parameters...

Checking sequences...
 1 sequences found: ['vot']
Found 1 valid sequence(s): ['vot']

Resolving particles simulations...
 No specific simulation settings found for 'vot'. Will fallback to database 'customdb' settings, if not intentional this might fails.
 1 particles simulations to compute... Simulations will attempt to run automatically using weather particle simulator
Create thread data/particles/customdb/vot/rain/25mm
START thread:  data/particles/customdb/vot/rain/25mm
 #0  In main menu
 #0  Apply options: {'cam_hz': 10, 'cam_CCD_WH': [1242, 375], 'cam_CCD_pixsize': 4.65, 'cam_WH': [1242, 375], 'cam_focal': 6, 'cam_gain': 20, 'cam_f_number': 6.0, 'cam_focus_plane': 6.0, 'cam_exposure': 2, 'cam_pos': [1.5, 1.5, 0.3], 'cam_lookat': [1.5, 1.5, -1.0], 'cam_up': [0.0, 1.0, 0.0], 'depth_scale': 1, 'render_scale': 1, 'sim_hz': 2000, 'sim_mode': 'normal', 'sim_duration': 34.0, 'sim_steps': {}, 'sequences': {'seq1': {'sim_mode': 'normal', 'sim_duration': 10}, 'seq2': {'sim_mode': 'steps', 'sim_steps': {'cam_motion': [100.0, 90.0, 80.0, 70.0, 60.0, 50.0, 40.0, 30.0, 20.0, 10.0, 0.0]}}, 'seq3': {'sim_mode': 'steps', 'sim_steps': {'rain_fallrate': [30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2]}}}}
 #0  In main menu
 #0     Save light map
 #0  Deactivating rain particles
 #0  Activating rain particles
 #0  Setting rain fallrate
 #0  In main menu
 #0  Starting simulation
Wait for threads
 #0  ERROR occured. Check the content of the log file to solve: data/particles/customdb/vot/rain/25mm/automate_log.txt
 #0  <pexpect.popen_spawn.PopenSpawn object at 0x7f22666efda0>
searcher: searcher_re:
    0: re.compile(b'Steps: What do you want to do \\?')
<pexpect.popen_spawn.PopenSpawn object at 0x7f22666efda0>
searcher: searcher_re:
    0: re.compile(b'Steps: What do you want to do \\?')
 #0  If starting python from an IDE, check LD_LIBRARY_PATH environment is accessible (https://youtrack.jetbrains.com/issue/PY-29580)
 sim. progress: All threads completed
Wait for threads
Thread ended:  data/particles/customdb/vot/rain/25mm
All threads completed
 All particles simulation completed
Something went wrong, cannot locate particles simulation file for sequence vot
Might crash later on

Running renderers...
Output directory: data/output/customdb

Sequence: vot
Traceback (most recent call last):
  File "main.py", line 233, in <module>
    generator.run()
  File "/home/fanqi/code/depth/rain-rendering/common/generator.py", line 202, in run
    sim_num = len(self.particles[sequence])
KeyError: 'vot'
```

**Comment by fanq15** [comment] 2021-12-22 06:37
It is similar to #10 , but the solution does not work for my case.

**Comment by rdecharette** [comment] 2021-12-22 09:54
Hello Fan, glad our research helps.

The problem is that the renderer cannot find the particles simulation for the sequence "vot" in the dataset "customdb". This is because, the renderer tries to run the particle simulation which seems to crash. 
1. is the particle simulation working when ran separately ? To test that, just run `./AHLSimulation` in the proper folder and start a simulation with entry `1`. After a few seconds, you should get an output like `00:00:00.500000000 (p#2624)`, if so that works.
2. if started from an IDE (eg. Pycharm) the simulator can work separately but fails when called from the renderer just because of libraries dependencies not being resolved when called from Python. Follow that [link](https://youtrack.jetbrains.com/issue/PY-29580) to seek a solution.

In any case, please post the content of `data/particles/customdb/vot/rain/25mm/automate_log.txt` to provide more info. 
Please let me know also if the standard [Kitti rendering](https://github.com/cv-rits/rain-rendering#kitti) worked for you as this is the simplest setup.

Finally, if your dataset has camera settings similar to kitti or cityscapes, you could directly use the simulation files provided at the bottom of [that page](data/particles/customdb/vot/rain/25mm/automate_log.txt) and duplicate them so that this folder structure exists `data/particles/customdb/vot/rain/25mm`. However, I do not recommend this solution that is very suboptimal as you won't be able to adjust any particle simulation settings.

**Comment by fanq15** [comment] 2021-12-22 10:46
Thank you very much for your quick and informative help!
For your question 1, yes, the `./AHLSimulation ` works well with entry `1`.
```
   SPECIAL SIMULATIONS
     101. Multiple simulations
     102. Step by step simulation
     103. Scenarios

What do you want to do ?
00:00:00.500000000 (p#2676)
00:00:01. (p#4428)
00:00:01.500000000 (p#4421)
00:00:02. (p#4472)
00:00:02.500000000 (p#4402)
00:00:03. (p#4503)
00:00:03.500000000 (p#4592)
00:00:04. (p#4312)
00:00:04.500000000 (p#4389)
00:00:05. (p#4416)
00:00:05.500000000 (p#4433)
00:00:06. (p#4336)
00:00:06.500000000 (p#4403)
```

For your question 2, I do not use IDE. I use the original terminal on a Ubuntu server.

I did not try the `KITTI` case, and I will try it.

I attach the `log.txt` file here.
[automate_log.txt](https://github.com/cv-rits/rain-rendering/files/7762103/automate_log.txt)

**Comment by rdecharette** [comment] 2021-12-22 11:35
I dug your issue, it seems to fail [here](https://github.com/cv-rits/rain-rendering/blob/6365f2077764320f0a1bd5244eda2a5489225230/tools/simulation.py#L422-L423) as it expects to be in a step simulation although you seem to run a normal simulation. My understanding is that this might be an issue in the code.

could you try replacing this line https://github.com/cv-rits/rain-rendering/blob/6365f2077764320f0a1bd5244eda2a5489225230/tools/simulation.py#L423 with this:
```python
            if _steps_menu:
                  self.interact_step_menu('1')
            else:
                  self.interact_main_menu('1')

```

**Anyhow**, please note that you will require to update the `config/customdb.py` file to fully control the simulation parameters. You should duplicate one of the [seq1/seq2/seq3 settings](https://github.com/cv-rits/rain-rendering/blob/6365f2077764320f0a1bd5244eda2a5489225230/config/customdb.py#L45-L58), and create a SEQUENCE setting (here, it seems your sequence name is "vot"). Because currently the `settings["sequences"]["vot"]` does not exist, the simulator falls back to default settings. Which should work yes, but you don't control the exact simulation parameters.

**Comment by fanq15** [comment] 2021-12-22 17:17
Thanks a lot for your patient help!
It works!!!! Thank you very much!

However, I found that the simulation speed is very slow, and I have lots of videos containing ~500k images.
Can I just simulate the longest video and apply the simulation to all other videos?

**Comment by rdecharette** [comment] 2021-12-22 17:28
Great ! Happy it works.

The complete simulation pipeline is made of two components:
1. Particle simulation > this is invariant to the scene photometry (ie. the image) so you can have N frames simulated, say 10, and apply that same N frames on any of your 500k images. Additionally, you'll note the particle simulation is just created once and then cached.
2. Particles rendering > this is dependent of the scene photometry (ie. the same particle simulation will result in different result for two different images). This relates to the illumination estimation of each drop. Hence normally, you should generate the rendering for each image.

That being said, have a look at our [multi-thread rendering script](https://github.com/cv-rits/rain-rendering#multi-threads-rendering) this is very significantly speeding up rendering. We did 390k rendering in a few days on a powerful desktop PC.
Similarly, the particle simulation can be rendered in [multi-thread with our script](https://github.com/cv-rits/rain-rendering#particles-simulator).
These tools are not really documented but for 500k they are worth checking out.
I'll close the issue since the current problem is solved.

**Comment by rdecharette** [comment] 2021-12-22 17:32
Was it my edit proposal [here](https://github.com/cv-rits/rain-rendering/issues/12#issuecomment-999509255) that solved ?
If so I'll patch the git.

**Comment by fanq15** [comment] 2021-12-23 02:47
Yes, it works in my case.
Thank you very much!

**Closed** 2021-12-23 12:58 UTC
